FROM jenkins/jenkins:lts-jdk17

USER root

# Docker CLI + docker-compose 설치
RUN apt-get update \
 && apt-get install -y docker.io curl \
 && curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64" \
    -o /usr/local/bin/docker-compose \
 && chmod +x /usr/local/bin/docker-compose \
 && apt-get clean

USER jenkins